# Generated by Django 5.1 on 2024-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=50.99, max_digits=10)),
                ('image', models.ImageField(blank=True, default='apple.jpg', upload_to='')),
            ],
        ),
    ]
